### ISSUE TITLE
Set up github actions to validate all PRs

### ISSUE THREAD

**Issue by cmungall** [GA4GH-Pedigree-Standard/family_history_terminology#18]
It looks like there is no validation happening on PRs

I would recommend adding this, and adding checks:

 - ensure you stay within the DL profile (it's easy to fall outside this when working with property chains and transitivity)
 - ensure ontology is consistent and coherent using HermiT

You may also want to consider a github action for releases, that materializes useful inferred axioms.

You can roll your own pipeline using robot to execute these, but I would recommend using ODK which will give you a Makefile with a target for tests, releases, etc as well as a docker container that can easily be deployed within github action https://github.com/INCATools/ontology-development-kit/

**Comment by ametke** [comment]
I have updated the actions to work for PRs. I also added a test to ensure the ontology stays within the DL profile. The other existing tests already ensure the ontology is consistent (using JFact rather than HermiT).

I have rolled my own for now but thanks for pointing me at ODK. I will try it out when I have a bit more time.
